// This file is automatically generated. Do not edit it directly.
// （生成物だが、開発用ダミーデータへの差し替えだけ手で足している。詳細は mem/ops/dev-fixtures.md）
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createFixtureClient } from '@/dev/fixtureClient';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// 開発時に限り、ログイン不要でダミーデータのまま全画面を確認できるモードに切り替える。
// `import.meta.env.DEV` を含むため、本番ビルドではこの分岐が定数 false に畳まれ、
// createFixtureClient ごと tree-shaking で消える（バンドルには入らない）。
const USE_DEV_FIXTURES = import.meta.env.DEV && import.meta.env.VITE_DEV_FIXTURES === 'true';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const realClient = () =>
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

export const supabase = (USE_DEV_FIXTURES
  ? createFixtureClient()
  : realClient()) as ReturnType<typeof realClient>;