import { cn } from "@/lib/utils";
import gymboardIcon from "@/assets/gymboard-loader.png";

type SizeKey = "xs" | "sm" | "md" | "lg" | "xl";

// Tailwind classes (not px numbers) so tailwind-merge can let a caller's own
// w-N h-N in className win over the preset — every current call site sizes
// via className, not the size prop.
const SIZE_CLASS_MAP: Record<SizeKey, string> = {
  xs: "w-3 h-3",
  sm: "w-4 h-4",
  md: "w-6 h-6",
  lg: "w-8 h-8",
  xl: "w-12 h-12",
};

interface DumbbellLoaderProps extends Omit<React.ImgHTMLAttributes<HTMLImageElement>, "size"> {
  size?: SizeKey | number;
  label?: string;
  className?: string;
}

/**
 * Unified app loader: the GymBoard app icon rises up from below, holds, and
 * sinks back down on a loop — stays upright (no rotation). The outer span is
 * a fixed-size, overflow-hidden "stage" so the rise/sink motion clips inside
 * the caller's box instead of spilling into surrounding inline content.
 * - Cycle: ~1.6s (ease-in-out, infinite)
 * - Accepts size preset (xs/sm/md/lg/xl) or numeric px.
 * - className lands on the outer span, so layout classes (mr-2, etc.) keep
 *   working when used as a drop-in replacement for Loader2.
 *
 * The artwork is the app icon with rounded corners (src/assets/gymboard-loader.png,
 * generated by scripts/generate-app-icon.py). It carries its own background, so it
 * stays visible on both the light app background and dark surfaces — the bare white
 * shield would disappear on light backgrounds.
 *
 * The name is historical: this rendered a dumbbell, then a World Cup trophy, and now
 * the app icon. Renaming would touch 40+ call sites, so it was left alone.
 */
export const DumbbellLoader = ({
  size = "md",
  label,
  className,
  ...props
}: DumbbellLoaderProps) => {
  const sizeClass = typeof size === "number" ? undefined : SIZE_CLASS_MAP[size];
  const sizeStyle = typeof size === "number" ? { width: size, height: size } : undefined;

  const icon = (
    <span
      className={cn("relative inline-block align-middle overflow-hidden", sizeClass, className)}
      style={sizeStyle}
    >
      <img
        src={gymboardIcon}
        alt=""
        className="absolute inset-0 w-full h-full object-contain animate-loader-rise"
        {...props}
      />
    </span>
  );

  if (!label) return icon;

  return (
    <div className="inline-flex items-center gap-2">
      {icon}
      <span className="text-sm text-muted-foreground">{label}</span>
    </div>
  );
};

export default DumbbellLoader;
